### ISSUE TITLE
cpu usage issue

### ISSUE THREAD

**Issue by gaodeng** [farhanfadila1717/slide_countdown#14]
Thank you very much for this library, the animation is very smooth, you did a really great job.

But I ran into a small problem with cpu usage. I have observed that this widget animation uses about 15% of cpu on my m1 macbook air. Tried slideDirection: SlideDirection.none, but the situation is still the same. Can you add a configuration to not show the animation at all, so that I can disable it when the window loses focus and save cpu resources?

**Comment by gaodeng** [comment]
Checked with DevTools' Highlight repaints and found that it seems that this animation causes the whole page to be repaint. Also tried wrapping a RepaintBoundary around it, no effect, still causes the whole page to be repaint

**Comment by farhanfadila1717** [comment]
Hi @gaodeng, are you in debug mode? i run it in simulator no issue 
Maybe you can try use new version [SlideCountdown 2.0.6](https://pub.dev/packages/slide_countdown)

**Comment by gaodeng** [comment]
> Hi @gaodeng, are you in debug mode? i run it in simulator no issue Maybe you can try use new version [SlideCountdown 2.0.6](https://pub.dev/packages/slide_countdown)

I'm testing the release build of the mac app.
I just tried 0.2.6-dev.1 with SlideDirection.none to remove the animation, and the cpu usage is normal.

However, if the animation is shown, it still takes up a lot of cpu. Through devtools, I can observe that the digit switch animation will cause the whole page to repaint, and when the page is complex, then the cpu usage will be high. But I don't quite understand why that animation will cause the whole page to repaint, maybe it's a bug inside the flutter framework?

**Comment by farhanfadila1717** [comment]
@gaodeng i tried it on my macbook air m1, but found no same problem.  If the `SlideCountdown` widget has animation it shouldn't repaint the whole page. Maybe you did that because there is a setState function in your page
Flutter version: 3.0.1.

**Comment by gaodeng** [comment]
@farhanfadila1717  Here is the code to reproduce the problem.

```dart

import 'package:flutter/material.dart';
import 'package:slide_countdown/slide_countdown.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const <Widget>[
            SlideCountdown(
              duration: Duration(days: 2),
            )
          ],
        ),
      ),
    );
  }
}

```
After running the app, Open flutter devtools and click the Highlight Repaints button in devtools.

Or you can check the video below, you will see that the whole page is repainting, not just the small part of SlideCountdown.

https://user-images.githubusercontent.com/1118249/172980616-d95399b6-1d3d-4e97-ac10-3f3da7eb6dbd.mp4

**Comment by synstin** [comment]
same issue
any update?

**Comment by farhanfadila1717** [comment]
fixed in `SlideCountdown` lastest version. The older code take a lot of `ValueNotifier`, the new version just only listen one stream. 
<img width="1440" alt="Screenshot 2023-11-16 at 12 52 27" src="https://github.com/farhanfadila1717/slide_countdown/assets/43161050/cbbad9ed-d47b-4db2-b0fa-36269871bd18">

**Comment by gaodeng** [comment]
I believe this issue should be reopened. I have tried the latest version, but the problem remains unresolved. This component still causes the entire page to repaint.
